name: Remote Server Cert Import

description: This action will install a certificate on a remote windows server.

inputs:
  remote-server:
    description: The fully qualified domain name or IP address of the remote server, for example "aserver.domain.com" or "127.0.0.1"
    required: true
  remote-user-name:
    description: 'The service account user name with permissions to install the certificate'
    required: true
  remote-user-password:
    description: 'The service account user password with permissions to install the certificate'
    required: true
  cert-path:
    description: Import cert path, for example "./certs/cert.pfx"
    required: true
  cert-store:
    description: Cert store import location, for example "Cert:\LocalMachine\My"
    required: true
  cert-password:
    description: The key value to use if the cert is locked
    required: false
    default: ''
  is-pfx-cert:
    description: Specifies if a cert is contains a private key, expects true or false, if true, cert-password must be specified
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Import Cert
      shell: Powershell
      run: |
        $args = @{
            remote_server = '${{ inputs.remote-server }}'
            remote_user_name = '${{ inputs.remote-user-name }}'
            remote_password = ConvertTo-SecureString "${{ inputs.remote-user-password }}" -AsPlainText -Force
            cert_path = '${{ inputs.cert-path }}'
            cert_store = '${{ inputs.cert-store }}'
            is_pfx_cert = $${{ inputs.is-pfx-cert }}
        }
        if( "${{ inputs.cert-password }}".Length -gt 0){
          $args['cert_password'] = ConvertTo-SecureString -String "${{ inputs.cert-password }}" -AsPlainText -Force
        }
        ${{ github.action_path }}/import-cert.ps1 @args
